{
  "bom": null,
  "run_details": {},
  "summary": {},
  "tool": "snyk",
  "vulnerabilities": [
    {
      "confidence": "",
      "file_location": null,
      "identifiers": {
        "cve": "CVE-2013-5123",
        "cwe": "CWE-300",
        "snyk": "SNYK-PYTHON-PIP-40230"
      },
      "is_excluded": false,
      "is_ignored": false,
      "language": "python",
      "metadata": {},
      "name": "pip:Man-in-the-Middle (MitM)",
      "overview": "Man-in-the-Middle (MitM) vulnerability in pip",
      "recommendation": "",
      "references": [],
      "severity": "medium",
      "version": "1.3",
      "vulnerability_type": "dependancy"
    },
    {
      "confidence": "",
      "file_location": null,
      "identifiers": {
        "cve": "CVE-2014-8991",
        "cwe": "CWE-400",
        "snyk": "SNYK-PYTHON-PIP-40297"
      },
      "is_excluded": false,
      "is_ignored": false,
      "language": "python",
      "metadata": {},
      "name": "pip:Denial of Service (DoS)",
      "overview": "Denial of Service (DoS) vulnerability in pip",
      "recommendation": "",
      "references": [],
      "severity": "medium",
      "version": "1.3",
      "vulnerability_type": "dependancy"
    },
    {
      "confidence": "",
      "file_location": null,
      "identifiers": {
        "cve": "CVE-2019-20916",
        "cwe": "CWE-22",
        "snyk": "SNYK-PYTHON-PIP-609855"
      },
      "is_excluded": false,
      "is_ignored": false,
      "language": "python",
      "metadata": {},
      "name": "pip:Directory Traversal",
      "overview": "Directory Traversal vulnerability in pip",
      "recommendation": "",
      "references": [],
      "severity": "high",
      "version": "1.3",
      "vulnerability_type": "dependancy"
    }
  ],
  "warnings": []
}